<a href="https://colab.research.google.com/github/pmcleod10/Data_Sci/blob/main/PerrinMcLeod_Stats_2023_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [ ]:
for i in range(100):
    print(i)

In [1]:
for i in range(5,8):   #showing every number between 5 and 8
    print(i)

5
6
7


In [ ]:
for i in range(3):
    print( "Test Number: " , i )

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [2]:
def square(x):   #defining what the square of x looks like
    return x**2

In [4]:
square(5)    #running a formula for the square of 5

25

In [5]:
square(square(2))     #squaring the square of 2

16

In [6]:
square(square(square(2)))   #squaring the square of 2 squared


256

In [7]:
square(123456)     #showing the square of larger numbers

15241383936

In [8]:
square(square(5))   #squaring the square

625

In [9]:
def add_two(x):    #defining that "add_two" means to add 2 to x
    return x+2

In [10]:
add_two(5)   #using the formula to add 2 to 5

7

In [11]:
square(add_two(5))    #squaring 5+2

49

### Logical Branching

In [ ]:
choice = "apple"

In [13]:
if choice == "apple":     #

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [12]:
choice = "orange"

In [ ]:
if choice == "apple":

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [ ]:
choice = "apple"

In [14]:
if choice == "apple":      #using selection to initate a response

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose oranges.
Thank you, shop again!


### User Input

In [ ]:
choice = input("Please enter your choice (i.e. apple): ")

Please enter your choice (i.e. apple): oranges


In [ ]:
choice

'oranges'

In [ ]:
if choice == "apple":

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose oranges.


#### Coins

In [17]:
import numpy as np

In [20]:
np.random.random()  #random number generator

0.6652780120563788

In [23]:
np.random.random() > 0.5 #taking the random number and defining it as larger or less than 0.5

True

In [24]:
def flip_coin():     #coin flipper based on if the number is larger or smaller than 0.5
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [25]:
flip_coin()


Heads


### Graphics Output

In [26]:
from IPython.core.display import display, HTML

In [27]:
display(HTML('<h1>Hello, world!</h1>'))

In [39]:
def coin():    #defining the term coin as a random number between 0-2
  return np.random.randint(2)

In [40]:
coin()

0

In [30]:

display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">'))

In [41]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg'
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'     #using images to distinguish between heads and tails

In [42]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [43]:
show_img(heads)    #heads images

In [44]:
show_img(tails)    #tails image

In [45]:
def flip_coin():    # using the term flip_coin to show either heads or tails

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [46]:
flip_coin()

In [47]:
for i in range(5):    # 5 random coin flips
    flip_coin()

In [38]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [ ]:
def shuffle(x):
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [ ]:
a = np.arange(52)

In [ ]:
shuffle(a)

In [ ]:
np.random.permutation(52)

### Speed Test

In [48]:
%%timeit
shuffle(a)

NameError: ignored

In [ ]:
%%timeit
np.random.permutation(52)

In [51]:
import numpy as np

In [52]:
np.random.permutation(52)

array([42, 44,  2, 28, 51, 33,  4, 17, 14, 36, 26, 32, 16, 49,  6, 24, 30,
       18, 15,  7,  0, 37, 11, 10, 21, 47, 13, 29, 39, 35,  3, 38,  5, 50,
        1, 40, 27, 46, 22,  8, 34, 12, 41, 23,  9, 25, 31, 48, 20, 43, 45,
       19])

In [53]:
cards = np.random.permutation(52)

In [54]:
cards

array([33, 44, 51, 31,  5, 16, 19, 36, 29, 41, 49, 11, 26, 50, 37,  2, 15,
       34, 14, 23, 40, 21, 17, 48, 43, 27,  1, 13, 25, 39, 42, 22,  6, 24,
       46, 35, 28,  8, 20,  0, 18, 45, 32,  3,  7,  4,  9, 30, 38, 12, 10,
       47])

In [55]:
cards[0]

33

In [56]:
cards[1]

44

In [57]:
cards[2]

51

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [59]:
np.arange(52).reshape(4,13)   #putting all 52 Cards in order

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [60]:
np.arange(52).reshape(4,13)%13   #putting all cards in order from ace-king (0-12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [61]:
np.arange(52).reshape(4,13)//13  #putting cards in order by suit

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [58]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']   # giving all of the cards names 

In [62]:
def card_name(card_number):   
    
    suit = card_number//13
    name = card_number%13

    return names[name] + " of " + suits[suit]

In [63]:
card_name(0)  # using "0" to pick a random Ace

'Ace of Clubs'

In [ ]:
card_name(51) 

'King of Diamonds'

In [64]:
cards = np.random.permutation(52)

In [65]:
top_of_deck         = card_name(cards[0])
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [66]:
top_of_deck, second_card_in_deck, last_card_in_deck

('Two of Hearts', 'Seven of Clubs', 'Ten of Hearts')

In [67]:
for i in range(5):       # 5 random card selector
    print(card_name(cards[i]))

Two of Hearts
Seven of Clubs
Eight of Clubs
Ace of Diamonds
Eight of Hearts


In [68]:
for i in range(15):     # 15 random card selector
    print(card_name(cards[i]))

Two of Hearts
Seven of Clubs
Eight of Clubs
Ace of Diamonds
Eight of Hearts
Four of Clubs
Six of Hearts
Six of Diamonds
Queen of Hearts
Seven of Spades
Ten of Diamonds
Two of Spades
Ace of Spades
Ace of Clubs
Jack of Spades


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [69]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/"   #giving cards images
card_url_tail = ".png"

In [74]:
suit = ['k','p','s','l']
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [75]:
i = np.random.randint(4)
j = np.random.randint(13)

In [76]:
i,j

(3, 9)

In [77]:
suit[i]

'l'

In [78]:
card[j]

'10'

In [79]:
from IPython.core.display import display, HTML

In [80]:
def show_img(img):
  display(HTML('<img src=' + img + '>'))

In [81]:
img = card_url_head + suit[i] + card[j] + card_url_tail    # applying number, suit and image together to select correct card

In [ ]:
show_img(img)

In [ ]:
def card_image(card_number):
    
    i = card_number//13
    j = card_number%13

    return suit[i]+card[j]

In [ ]:
card_image(3)

'k4'

In [ ]:
img = card_url_head + card_image(3) + card_url_tail

In [ ]:
show_img(img)

In [ ]:
for i in range(52):
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)